export enum Entities {
  USER = 'USER',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  ROLE_PERMISSION = 'ROLE_PERMISSION',
  COURSE = 'COURSE',
  USER_COURSE = 'USER_COURSE',
  SCHEDULE = 'SCHEDULE',
  QUIZ = 'QUIZ',
  QUESTION = 'QUESTION',
  ANSWER = 'ANSWER',
  QUESTION_FEEDBACK = 'QUESTION_FEEDBACK',
  SESSION = 'SESSION',
}
